# fly.toml app configuration file generated for cutaboveshop on 2023-07-24T21:26:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cutaboveshop"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
